name: Publish Beta

on:
  push:
    branches:    
      - 'master'
  release:
    types: [prereleased]

jobs:
  build:
    # needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install deps 
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install 

      - name: Build package
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-upload
          path: |
            dist

  desktop-build:
      needs: build
      strategy:
        fail-fast: false
        matrix:
          platform: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.platform }}

      permissions:
        packages: write
        contents: read

      steps:
        - uses: actions/checkout@v2

        # - name: Download a single artifact
        # - uses: actions/download-artifact@v3
        #   with:
        #     name: dist-upload

        - name: Get release
          id: get_release
          uses: bruceadams/get-release@v1.2.3
          env:
            GITHUB_TOKEN: ${{ github.token }}

        - uses: tauri-apps/tauri-action@v0
          with:
            releaseId: ${{ steps.get_release.outputs.id }}
